// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WeekendCarSales.Infrastructure.Database;

#nullable disable

namespace WeekendCarSales.Infrastructure.Database.Migrations
{
    [DbContext(typeof(WeekendCarSalesDbContext))]
    partial class WeekendCarSalesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("WeekendCarSales.Infrastructure.Database.Models.CarSale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PriceWithoutVat")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PriceWithoutVat");

                    b.Property<DateTime>("SoldOn")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("VatRate")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("VatRate");

                    b.HasKey("Id");

                    b.ToTable("CarSales", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
